# Generated by Django 4.0 on 2022-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ifc2Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('time_stamp', models.DateTimeField(max_length=200, null=True)),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('schema_identifiers', models.CharField(max_length=200, null=True)),
                ('software', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
